
site_name: 'Insper: Open Source Conformance Tester for TAGs EPC-GEN2 UHF RFID'

theme:
  features:
    - instant
    - navigation.expand
    - tabs: true
  name: 'readthedocs'
  palette:
      primary: 'white'
      accent: 'pink'
  font:
    text: Roboto
    code: Roboto Mono
  highlightjs: true
  hljs_languages:
      - C

# Copyright
copyright: 'Copyright &copy; 2021 / Prof. Rafael Corsi / rafael.corsi@insper.edu.br'

# repo
docs_dir: docs-src
site_dir: docs

# CSS
extra_css:
- css/extra.css

nav:
  - Home: index.md
  - getting_started.md
  - hardware.md
  - IP_core_interface.md
  - firmware.md
  - tests.md
  - Doxygen: https://pfeinsper.github.io/21b-indago-rfid-conformance-tester/doxygen/
  
# Extensions
markdown_extensions:
  - markdown.extensions.attr_list
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
    - search
